/** USER ACTIONS **/
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';

export const SHOW_LOGIN_SPINNER = 'SHOW_LOGIN_SPINNER';

/** AUTHENTICATION **/
export const LOGIN_GOOGLE_REQUEST = 'LOGIN_GOOGLE_REQUEST';

/** CONFIG */
export const FETCH_CONFIG = 'FETCH_CONFIG';
export const REFRESH_CONFIG = 'REFRESH_CONFIG';

/** MODAL ACTIONS **/
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

/** CONTACT */
export const GET_CONTACT = 'GET_CONTACT';
export const UPDATE_CURRENT_CONTACT = 'UPDATE_CURRENT_CONTACT';

/** CONTACTS */
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const REFRESH_CONTACTS = 'REFRESH_CONTACTS';

/** EVENTS */
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const GET_EVENTS = 'GET_EVENTS';
export const REFRESH_EVENTS = 'REFRESH_EVENTS';
export const CREATE_EVENT = 'CREATE_EVENT';

/* ASYNC */
export const SUBMIT_DONOR_CODE = 'SUBMIT_DONOR_CODE';
export const ASYNC_FORM_STATUS_UPDATE = 'ASYNC_FORM_STATUS_UPDATE';
export const RESPONSE_CODE_SUCCESS = 200;
export const RESPONSE_CODE_FAIL = 400;
export const PLACE_ORDER_RESPONSE = 'PLACE_ORDER_RESPONSE';
export const CLEAR_ORDER_RESPONSES = 'CLEAR_ORDER_RESPONSES';

// old
export const AUTH_CHECK_REQUEST = 'AUTH_CHECK_REQUEST';
export const AUTH_CHECK_RESPONSE = 'AUTH_CHECK_RESPONSE';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOCKDOWN_MODE = 'LOCKDOWN_MODE';
export const SET_USER = 'SET_USER';
export const GET_CONFIG_SUCCESS = 'GET_CONFIG_SUCCESS';
export const UPDATE_CONFIG_SUCCESS = 'UPDATE_CONFIG_SUCCESS';
