/** USER ACTIONS **/
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';

export const SHOW_LOGIN_SPINNER = 'SHOW_LOGIN_SPINNER';

/** AUTHENTICATION **/
export const LOGIN_GOOGLE_REQUEST = 'LOGIN_GOOGLE_REQUEST';

/** CONFIG */
export const FETCH_CONFIG = 'FETCH_CONFIG';
export const REFRESH_CONFIG = 'REFRESH_CONFIG';

/** MODAL ACTIONS **/
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

/** NOTIFICATIONS */
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const UPDATE_NOTIFICATION_SINGLETON = 'UPDATE_NOTIFICATION_SINGLETON';
export const NOTIFICATION_SAVE_SUCCESS = 'NOTIFICATION_SAVE_SUCCESS';
export const NOTIFICATION_SAVE_FAIL = 'NOTIFICATION_SAVE_FAIL';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';

/** INTAKE FORM */
export const UPDATE_INTAKE_FORM_FIELD = 'UPDATE_INTAKE_FORM_FIELD';
export const UPDATE_INTAKE_FORM_WITH_CONTACT = 'UPDATE_INTAKE_FORM_WITH_CONTACT';
export const SET_INTAKE_FORM_TO_INITIAL_STATE = 'SET_INTAKE_FORM_TO_INITIAL_STATE';

/** CONTACT */
export const GET_CONTACT = 'GET_CONTACT';
export const UPDATE_CURRENT_CONTACT = 'UPDATE_CURRENT_CONTACT';
export const GET_EVENTS_FOR_CONTACT = 'GET_EVENTS_FOR_CONTACT';
export const UPDATE_CURRENT_CONTACT_WITH_EVENTS = 'UPDATE_CURRENT_CONTACT_WITH_EVENTS';

/** CONTACTS */
export const SEARCH_CONTACTS = 'SEARCH_CONTACTS';
export const SET_CONTACT_SEARCH_RESULTS = 'SET_CONTACT_SEARCH_RESULTS';
export const SET_CURRENT_SEARCH_QUERY = 'SET_CURRENT_SEARCH_QUERY';

/** EVENTS */
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const GET_EVENTS = 'GET_EVENTS';
export const REFRESH_EVENTS = 'REFRESH_EVENTS';
export const CREATE_EVENT = 'CREATE_EVENT';

/* ASYNC */
// TODO: cleanup (delete) this leftover code from PMC app
export const SUBMIT_DONOR_CODE = 'SUBMIT_DONOR_CODE';
export const ASYNC_FORM_STATUS_UPDATE = 'ASYNC_FORM_STATUS_UPDATE';
export const RESPONSE_CODE_SUCCESS = 200;
export const RESPONSE_CODE_FAIL = 400;
export const PLACE_ORDER_RESPONSE = 'PLACE_ORDER_RESPONSE';
export const CLEAR_ORDER_RESPONSES = 'CLEAR_ORDER_RESPONSES';

/** SEARCH */
export const REQUEST_SEARCH_BY_CRITERIA = 'REQUEST_SEARCH_BY_CRITERIA';
export const UPDATE_SEARCH_BY_CRITERIA_CRITERIA = 'UPDATE_SEARCH_BY_CRITERIA_CRITERIA';
export const UPDATE_SEARCH_BY_CRITERIA_RESULTS = 'UPDATE_SEARCH_BY_CRITERIA_RESULTS';

/** CONSENT */
export const GET_CONSENT_TEXT = 'GET_CONSENT_TEXT';
export const UPDATE_CONSENT_TEXT = 'UPDATE_CONSENT_TEXT';

/** REPORTS */
export const FETCH_REPORTS_DATA = 'FETCH_REPORTS_DATA';
export const UPDATE_REPORTS_DATA = 'UPDATE_REPORTS_DATA';
export const RANGE_CURRENT_WEEK = 'RANGE_CURRENT_WEEK';
export const RANGE_PREVIOUS_WEEK = 'RANGE_PREVIOUS_WEEK';
export const RANGE_CURRENT_YEAR = 'RANGE_CURRENT_YEAR';
export const RANGE_PREVIOUS_YEAR = 'RANGE_PREVIOUS_YEAR';
export const RANGE_ALL_TIME = 'RANGE_ALL_TIME';

// old
export const AUTH_CHECK_REQUEST = 'AUTH_CHECK_REQUEST';
export const AUTH_CHECK_RESPONSE = 'AUTH_CHECK_RESPONSE';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOCKDOWN_MODE = 'LOCKDOWN_MODE';
export const SET_USER = 'SET_USER';
export const GET_CONFIG_SUCCESS = 'GET_CONFIG_SUCCESS';
export const UPDATE_CONFIG_SUCCESS = 'UPDATE_CONFIG_SUCCESS';

